#ifndef CC_RESERVED_IDS_HEADER
#define CC_RESERVED_IDS_HEADER

//! Unique IDs reserved by CloudCompare for special entities (display elements, etc.)
/** They should all remain below ccUniqueIDGenerator::MinUniqueID (256)
**/
enum class ReservedIDs : unsigned
{
	CLIPPING_BOX = 1,
	INTERACTIVE_SEGMENTATION_TOOL_POLYLINE = 2,
	INTERACTIVE_SEGMENTATION_TOOL_POLYLINE_VERTICES = 3,
	TRACE_POLYLINE_TOOL_POLYLINE_TIP = 4,
	TRACE_POLYLINE_TOOL_POLYLINE_TIP_VERTICES = 5,
	TRACE_POLYLINE_TOOL_POLYLINE = 6,
	TRACE_POLYLINE_TOOL_POLYLINE_VERTICES = 7,
};

#endif //CC_RESERVED_IDS_HEADER
